jira = "https://infiniteorbits-tls.atlassian.net"

[[scenario]]
name = "[Auto Boot] Boot from valid payload with fallback"
file = "boot_sw/BSW_01_Auto_boot/BSW_01_02_ABPF.puml"

[[scenario]]
name = "[Manual Boot] Validate Boot From All Slots"
file = "boot_sw/BSW_02_Manual_boot/BSW_02_01_MBAS.puml"
