/' ORB-96 – [Auto Boot] Fallback to Redundant Payload

This scenario validates that, upon power-up or reset, the OrbSight V2 platform 
successfully boots from the redundant payload stored in the secondary eMMC after rejecting
the primary payload. The system must load both FreeRTOS (hart4) 
and U-Boot (hart1–3). FreeRTOS must emit a heartbeat, and Linux should boot into userspace.

Covered requirements:
- ORB-5: Software image boot
- ORB-6: Boot report generation
- ORB-7: Software image identification by boot SW
- ORB-8: Boot report accessibility
- ORB-12: Independent execution of Linux and FreeRTOS
- ORB-13: Execution time of software image
- ORB-15: The boot SW interface requirement
- ORB-101: Payload integrity validation (MD5)
- ORB-102: Fallback to Redundant Payload
- ORB-104: Payload composition (FreeRTOS + U-Boot)
- ORB-106: Boot Report on Linux
- ORB-85: Heartbeat Feature
'/

@startuml ORB-96: [Auto Boot] Fallback to Redundant Payload
!include ../../params.puml
!include ../../conf.puml
!include ../../macros.puml

title
  |= Parameter |= Test Case |
  | @BootSource | Redundat Payload (secondary eMMC) |
end title

:Flash a payload with invalid MD5 hash with FreeRTOS, U-Boot payload and Linux image to primary eMMC;
:Flash a payload with valid MD5 hash with FreeRTOS, U-Boot payload and Linux image to secondary eMMC;
:Reboot the system;
:Wait 20 seconds for boot to complete;

$simAction():Start monitoring CAN bus;
fork
:Download boot report from Linux;
$simCheck():* HSS selects  redundant payload slot
* Redundant payload MD5 hash check passes
* HSS refuses to load the primary payload (MD5 check rejection)
* Redundant Payload is loaded into DDR
* U-Boot starts on HARTs U54_1–3
* Linux kernel boots and enters userspace}
$req("ORB-5")
$req("ORB-6")
$req("ORB-7")
$req("ORB-8")
$req("ORB-15 (partially)")
$req("ORB-101")
$req("ORB-102")
$req("ORB-106")
fork again
:Observe CAN activity from FreeRTOS;
$simCheck():* Software image boot in less than 20 seconds
* FreeRTOS starts on HART U54_4
* Periodic CAN heartbeat messages detected}
$req("ORB-12")
$req("ORB-13")
$req("ORB-104")
$req("ORB-85")
end fork
$simAction(): Stop monitoring CAN bus;

stop
@enduml
